AdminHotelApi/Controllers/Api/TiposHabitacionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using AdminHotelApi.Data;
using AdminHotelApi.Models;
using AdminHotelApi.Models.Dtos;
using AdminHotelApi.Models.Entities;
using Global;

namespace AdminHotelApi.Controllers.Api
{
    public class TiposHabitacionesController : ApiController
    {
        private AdminHotelApiContext db = new AdminHotelApiContext();

        // GET: api/TiposHabitaciones
        [ResponseType(typeof(ResultadoDto<IEnumerable<TipoHabitacionDto>>))]
        public IHttpActionResult GetTiposHabitaciones()
        {
            List<TipoHabitacion> tiposHabitaciones = db.TiposHabitaciones
                .Where(x => x.HotelId == Constantes.HotelId && x.Activo).ToList();

            List<TipoHabitacionDto> tiposHabitacionesDto = new List<TipoHabitacionDto>();

            foreach (var tipoHabitacion in tiposHabitaciones.Select(x => Utilerias.Mapeador<TipoHabitacionDto, TipoHabitacion>(x)))
            {
                tipoHabitacion.Hotel = Utilerias
                    .Mapeador<HotelDto, Hotel>(db.Hoteles
                    .Where(x => x.HotelId == tipoHabitacion.HotelId).First());

                TipoHabitacionFoto foto = db.TiposHabitacionesFotos
                    .Where(x => x.HotelId == tipoHabitacion.HotelId && x.TipoHabitacionId == tipoHabitacion.TipoHabitacionId).FirstOrDefault();

                if (foto.IsNotNull())
                {
                    tipoHabitacion.Foto = new ArchivoDto
                    {
                        Nombre = foto.Nombre,
                        Contenido = foto.Contenido
                    };
                }
                tiposHabitacionesDto.Add(tipoHabitacion);
            }

            return Ok(new ResultadoDto<IEnumerable<TipoHabitacionDto>>
            {
                Datos = tiposHabitacionesDto
            });
        }

        // GET: api/TiposHabitaciones/5
        [ResponseType(typeof(TipoHabitacionDto))]
        public IHttpActionResult GetTipoHabitacion(int id)
        {
            TipoHabitacion tipoHabitacion = db.TiposHabitaciones.Find(Constantes.HotelId, id);
            if (tipoHabitacion == null)
            {
                return NotFound();
            }
            TipoHabitacionDto tipoHabitacionDto = Utilerias.Mapeador<TipoHabitacionDto, TipoHabitacion>(tipoHabitacion);
            tipoHabitacionDto.Hotel = Utilerias
                    .Mapeador<HotelDto, Hotel>(db.Hoteles
                    .Where(x => x.HotelId == tipoHabitacionDto.HotelId).First());

            return Ok(new ResultadoDto<TipoHabitacionDto>
            {
                Datos = tipoHabitacionDto
            });
        }

        // PUT: api/TiposHabitaciones/5
        [ResponseType(typeof(ResultadoDto))]
        public IHttpActionResult PutTipoHabitacion(int id, TipoHabitacionDto tipoHabitacion)
        {
            if (id != tipoHabitacion.TipoHabitacionId)
            {
                return BadRequest();
            }

            TipoHabitacion currentTipoHabitacion = db.TiposHabitaciones.Find(Constantes.HotelId, id);

            currentTipoHabitacion.Nombre = tipoHabitacion.Nombre;
            currentTipoHabitacion.Descripcion = tipoHabitacion.Descripcion;
            currentTipoHabitacion.FechaUpdate = DateTime.Now;

            db.Entry(currentTipoHabitacion).State = EntityState.Modified;
            db.SaveChanges();

            tipoHabitacion.HotelId = currentTipoHabitacion.HotelId;
            tipoHabitacion.TipoHabitacionId = currentTipoHabitacion.TipoHabitacionId;
            ActualizarTipoHabitacionFoto(tipoHabitacion);
            return Ok(new ResultadoDto
            {
                Mensaje = "El tipo de habitación se actualizó correctamente."
            });
        }

        // POST: api/TiposHabitaciones
        [ResponseType(typeof(ResultadoDto<TipoHabitacionDto>))]
        public IHttpActionResult PostTipoHabitacion(TipoHabitacionDto tipoHabitacion)
        {
            int tipoHabitacionId = (db.TiposHabitaciones
                    .Where(x => x.HotelId == Constantes.HotelId)
                    .Max(x => (int?)x.TipoHabitacionId) ?? 0) + 1;

            tipoHabitacion.TipoHabitacionId = tipoHabitacionId;
            tipoHabitacion.HotelId = Constantes.HotelId;

            var nuevoTipoHabitacion = db.TiposHabitaciones.Add(Utilerias.Mapeador<TipoHabitacion, TipoHabitacionDto>(tipoHabitacion));
            db.SaveChanges();

            GuardarTipoHabitacionFoto(tipoHabitacion);
            return Created(string.Empty, new ResultadoDto<TipoHabitacionDto>
            {
                Mensaje = "El tipo de habitación se guardó correctamente.",
                Datos = Utilerias.Mapeador<TipoHabitacionDto, TipoHabitacion>(nuevoTipoHabitacion)
            });
        }

        private void GuardarTipoHabitacionFoto(TipoHabitacionDto tipoHabitacion)
        {
            int tipoHabitacionFotoId = (db.TiposHabitacionesFotos
                              .Where(x => x.HotelId == tipoHabitacion.HotelId)
                              .Max(x => (int?)x.TipoHabitacionId) ?? 0) + 1;

            TipoHabitacionFoto tipoHabitacionFoto = Utilerias.Mapeador<TipoHabitacionFoto, ArchivoDto>(tipoHabitacion.Foto);

            tipoHabitacionFoto.TipoHabitacionFotoId = tipoHabitacionFotoId;
            tipoHabitacionFoto.HotelId = tipoHabitacion.HotelId;
            tipoHabitacionFoto.TipoHabitacionId = tipoHabitacion.TipoHabitacionId;

            db.TiposHabitacionesFotos.Add(tipoHabitacionFoto);
            db.SaveChanges();
        }

        private void ActualizarTipoHabitacionFoto(TipoHabitacionDto tipoHabitacion)
        {
            TipoHabitacionFoto foto = db.TiposHabitacionesFotos
                    .Where(x => x.HotelId == tipoHabitacion.HotelId && x.TipoHabitacionId == tipoHabitacion.TipoHabitacionId).FirstOrDefault();

            if (foto.IsNotNull())
            {
                foto.Nombre = tipoHabitacion.Foto.Nombre;
                foto.Contenido = tipoHabitacion.Foto.Contenido;
                foto.FechaUpdate = DateTime.Now;

                db.Entry(foto).State = EntityState.Modified;
                db.SaveChanges();
            }
        }

        // DELETE: api/TiposHabitaciones/5
        [ResponseType(typeof(ResultadoDto))]
        public IHttpActionResult DeleteTipoHabitacion(int id)
        {
            TipoHabitacion tipoHabitacion = db.TiposHabitaciones.Find(Constantes.HotelId, id);
            if (tipoHabitacion == null)
            {
                return NotFound();
            }

            tipoHabitacion.FechaUpdate = DateTime.Now;
            tipoHabitacion.Activo = false;

            db.Entry(tipoHabitacion).State = EntityState.Modified;
            db.SaveChanges();

            return Ok(new ResultadoDto
            {
                Mensaje = "El tipo de habitación se elimino correctamente."
            });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool TipoHabitacionExists(int id)
        {
            return db.TiposHabitaciones.Count(e => e.HotelId == id) > 0;
        }
    }
}

AdminHotelApi/Controllers/TiposHabitacionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdminHotelApi.Data;
using AdminHotelApi.Models;
using AdminHotelApi.Models.Dtos;
using AdminHotelApi.Models.Entities;
using Global;

namespace AdminHotelApi.Controllers
{
    public class TiposHabitacionesController : Controller
    {
        private AdminHotelApiContext db = new AdminHotelApiContext();

        // GET: TiposHabitaciones
        public ActionResult Index()
        {
            var tiposHabitaciones = db.TiposHabitaciones.Include(t => t.Hotel);
            return View(tiposHabitaciones.ToList());
        }

        // GET: TiposHabitaciones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoHabitacion tipoHabitacion = db.TiposHabitaciones.Find(id);
            if (tipoHabitacion == null)
            {
                return HttpNotFound();
            }
            return View(tipoHabitacion);
        }

        // GET: TiposHabitaciones/Create
        public ActionResult Create()
        {
            ViewBag.HotelId = new SelectList(db.Hoteles, "HotelId", "Nombre");
            return View();
        }

        // POST: TiposHabitaciones/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TipoHabitacionDto tipoHabitacionDto)
        {
            TipoHabitacion tipoHabitacion =
                    Utilerias.Mapeador<TipoHabitacion, TipoHabitacionDto>(tipoHabitacionDto);

            TipoHabitacionFoto tipoHabitacionFoto = Utilerias.Mapeador<TipoHabitacionFoto, ArchivoDto>(
                Project.PostedFileToDto(tipoHabitacionDto.UploadFoto));

            if (ModelState.IsValid)
            {
                int tipoHabitacionId = db.TiposHabitaciones
                    .Where(x => x.HotelId == 1)
                    .Max(x => (int?)x.TipoHabitacionId) ?? 0;

                tipoHabitacion.TipoHabitacionId = tipoHabitacionId + 1;

                int tipoHabitacionFotoId = db.TiposHabitacionesFotos
                    .Where(x => x.HotelId == tipoHabitacion.HotelId && x.TipoHabitacionId == tipoHabitacion.TipoHabitacionId)
                    .Max(x => (int?)x.TipoHabitacionId) ?? 0;

                tipoHabitacionFoto.TipoHabitacionFotoId = tipoHabitacionFotoId + 1;
                tipoHabitacionFoto.HotelId = tipoHabitacion.HotelId;
                tipoHabitacionFoto.TipoHabitacionId = tipoHabitacion.TipoHabitacionId;
                tipoHabitacionFoto.Activo = true;
                tipoHabitacionFoto.FechaAlta = tipoHabitacion.FechaAlta;

                db.TiposHabitaciones.Add(tipoHabitacion);
                db.TiposHabitacionesFotos.Add(tipoHabitacionFoto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.HotelId = new SelectList(db.Hoteles, "HotelId", "Nombre", tipoHabitacion.HotelId);
            return View(tipoHabitacion);
        }

        // GET: TiposHabitaciones/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoHabitacion tipoHabitacion = db.TiposHabitaciones.Find(id);
            if (tipoHabitacion == null)
            {
                return HttpNotFound();
            }
            ViewBag.HotelId = new SelectList(db.Hoteles, "HotelId", "Nombre", tipoHabitacion.HotelId);
            return View(tipoHabitacion);
        }

        // POST: TiposHabitaciones/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "HotelId,TipoHabitacionId,Nombre,Capacidad,Activo,FechaAlta,FechaUpdate")] TipoHabitacion tipoHabitacion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipoHabitacion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HotelId = new SelectList(db.Hoteles, "HotelId", "Nombre", tipoHabitacion.HotelId);
            return View(tipoHabitacion);
        }

        // GET: TiposHabitaciones/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoHabitacion tipoHabitacion = db.TiposHabitaciones.Find(id);
            if (tipoHabitacion == null)
            {
                return HttpNotFound();
            }
            return View(tipoHabitacion);
        }

        // POST: TiposHabitaciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TipoHabitacion tipoHabitacion = db.TiposHabitaciones.Find(id);
            db.TiposHabitaciones.Remove(tipoHabitacion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdminHotelApi/Views/TiposHabitaciones/Create.cshtml
@model AdminHotelApi.Models.TipoHabitacion

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "TiposHabitaciones", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TipoHabitacion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HotelId, "HotelId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HotelId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HotelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoHabitacionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoHabitacionId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoHabitacionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activo)
                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaAlta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaAlta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaAlta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaUpdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaUpdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaUpdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Foto</label>
            <div class="col-md-10">
                @Html.TextBox("UploadFoto", "", new { type = "file" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

AdminHotelApi/Views/TiposHabitaciones/Delete.cshtml
@model AdminHotelApi.Models.TipoHabitacion

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TipoHabitacion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Hotel.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hotel.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capacidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaAlta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaAlta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaUpdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaUpdate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AdminHotelApi/Views/TiposHabitaciones/Details.cshtml
@model AdminHotelApi.Models.TipoHabitacion

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TipoHabitacion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Hotel.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hotel.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capacidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaAlta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaAlta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaUpdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaUpdate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AdminHotelApi/Views/TiposHabitaciones/Edit.cshtml
@model AdminHotelApi.Models.TipoHabitacion

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TipoHabitacion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.HotelId)

        @Html.HiddenFor(model => model.TipoHabitacionId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capacidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activo)
                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaAlta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaAlta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaAlta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaUpdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaUpdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaUpdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

AdminHotelApi/Views/TiposHabitaciones/Index.cshtml
@model IEnumerable<AdminHotelApi.Models.TipoHabitacion>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>Hotel</th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Activo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaAlta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaUpdate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Hotel.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Activo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaAlta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaUpdate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }

</table>